project_id = "mwwjrrduavfcwjiyniuy"

[functions.send-newsletter]
verify_jwt = true

[functions.marketing-unsubscribe]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-usdt]
verify_jwt = false

[functions.naboopay-webhook]
verify_jwt = false

[functions.get-client-infos]
verify_jwt = true

[functions.auto-cancel-stale-orders]
verify_jwt = false