// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwwjrrduavfcwjiyniuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13d2pycmR1YXZmY3dqaXluaXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTEwNjgsImV4cCI6MjA2NDY2NzA2OH0.izReQBVYj_iCxC3aI-nMjspnnIbz8W3L-8HUB0k9R3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);